/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

sourceSets.main.get().java.srcDir("src")
sourceSets.test.get().java.srcDir("test")

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")
    implementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // ASM library for JVM bytecode generation (Phase 4)
    implementation("org.ow2.asm:asm:9.7.1")
    implementation("org.ow2.asm:asm-util:9.7.1")     // utile pour debug (Textifier, CheckClassAdapter)
    implementation("org.ow2.asm:asm-commons:9.7.1")  // utile si on veut utiliser GeneratorAdapter
}

application {
    // Define the main class for the application.
    mainClass.set("compiler.Compiler")
}

// Ajout d'une tâche JavaExec pour lancer le Parser directement.
// Utilisation: gradlew runParser -PappArgs="-parser src/main/java/compiler/Lexer/code_example.txt"
tasks.register<JavaExec>("runParser") {
    group = "application"
    description = "Run the Compiler with -parser to parse a file. Pass arguments via -PappArgs=\"-parser file\""
    classpath = sourceSets["main"].runtimeClasspath
    // Exécuter la classe Compiler qui gère l'option -parser
    mainClass.set("compiler.Compiler")

    // Read appArgs project property (split on whitespace) if provided
    val appArgs = if (project.hasProperty("appArgs")) (project.property("appArgs") as String).trim() else ""
    if (appArgs.isNotEmpty()) {
        args = appArgs.split("\\s+".toRegex())
    }
}