/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Lexer.Lexer;
import compiler.Lexer.Lexer.Sym;
import compiler.Lexer.Symbol;
import compiler.Parser.Parser;
import compiler.Parser.ProgramNode;
import compiler.SemanticAnalysis.SemanticAnalysis;
import compiler.SemanticAnalysis.SemanticException;

public class Compiler {
    public static void main(String[] args) {

        System.out.println(args.length);
        if (args.length < 2){
            System.out.println("pas assez d'arguments");
            return;
        }

        if (args[0].equals("-lexer")){
            try {
                Lexer lexer = new Lexer(new java.io.FileReader(args[1]));
                Symbol sym;

                System.out.println("analyse\n");

                while ((sym = lexer.getNextSymbol()).sym != Sym.EOF) {
                    System.out.println(sym);
                }

                System.out.println("\n fin");

            } catch (Exception e) {
                System.err.println("Erreur: " + e.getMessage());
                e.printStackTrace();
            }
        }

        // Nouvelle option: -parser <fichier>
        else if (args[0].equals("-parser")) {
            try {
                Lexer lexer = new Lexer(new java.io.FileReader(args[1]));
                Parser parser = new Parser(lexer);
                ProgramNode ast = parser.getAST();
                System.out.println("AST:");
                ast.print("");
            } catch (Exception e) {
                System.err.println("Erreur lors de l'analyse: " + e.getMessage());
                e.printStackTrace();
            }
        }
        else if (args[0].equals("-semantic")) {
            try {
                // 1. Lexing + Parsing
                Lexer lexer = new Lexer(new java.io.FileReader(args[1]));
                Parser parser = new Parser(lexer);
                ProgramNode ast = parser.getAST();

                // 2. Analyse sémantique
                SemanticAnalysis sa = new SemanticAnalysis();
                sa.analyze(ast);

                System.out.println("Analyse semantique reussie.");

            } catch (SemanticException e) {
                // Erreur sémantique : message avec le mot-clé (TypeError, ScopeError, ...)
                System.err.println(e.getMessage());
                System.exit(2);

            } catch (Exception e) {
                // Erreur de lecture ou de parsing
                System.err.println("Erreur: " + e.getMessage());
                e.printStackTrace();
                System.exit(1);
            }

        } else {
            System.err.println("Option inconnue: " + args[0]);
            System.err.println("Usage: -lexer <file> | -parser <file> | -semantic <file>");
            System.exit(1);
        }

    }

}
